### PR TITLE
Remove broken fonts stylesheet

### PR DESCRIPTION
**Pull request by madsmtm**
EDIT: Pretty sure the failed CI checks are not my fault

### CODE REVIEW

**Comment by abitrolly** [comment]
Maybe the missing stylesheet is the reason why https://cheat.sh in browser looks different than in curl.

**Comment by madsmtm** [comment]
Maybe? Though it's been missing since the creation of this repo, so hard to tell

**Comment by abitrolly** [comment]
You're right. There is [no evidence](https://github.com/chubin/cheat.sh/commits/master/share/ansi2html.sh) that this .css file existed. The `ansi2html.sh` seems modified from original https://github.com/pixelb/scripts/blame/e3afc9ed79443e80fba8a509d656b667b2674015/scripts/ansi2html.sh

Getting back the original and updating it to the latest version may fix the failing tests https://github.com/chubin/cheat.sh/pull/269

**Comment by abitrolly** [comment]
Let's merge this and move on. I am sure @chubin enlighten us on the history of that file when he finds the time.

**Comment by chubin** [comment]
@abitrolly I think this file was used in some initial implementation that predates the git repo. Thank you for fixing it!

**Comment by abitrolly** [comment]
@chubin the credit belongs to @madsmtm. :D

**Comment by chubin** [comment]
@abitrolly Absolutely

@madsmtm Thanks a lot!

**Pull request merged**
