### PR TITLE
refactor colorize_internal.py

### PR DESCRIPTION
**Pull request by StrikingLoo**
Good morning!
I did a few refactors on some of the functions defined in the colorize_internal.py code.
I added an option to pass color codes as strings, though I did not use it, since I think future maintainers of the code may find that easier.
I also tried to unclutter the long functions, and as always will be thankful if you made sure the code still works as intented.

I hope you find the changes useful!

### CODE REVIEW

**Comment by lawenda5** [comment]
Hi , I have problem in my program Windows nothing work really good . I push code nothing work in computer. I trying I laptop same not working good I don't know where is problem maybe someone block me everytime. I trying to much time and spend to much time computer , tablet and laptop .

**Comment by lawenda5** [comment]
I push just homegroup only so I don't know where problem's . Code .

**Comment by chubin** [comment]
@StrikingLoo Hi! Probably yes but please give me a little bit more time, I'm very busy now, but I hope it will be better soon

**Comment by chubin** [comment]
@StrikingLoo Luciano, thank you very much for your pull request!
I'm sorry for the delay, I am back now and I hope that I will have more time for the project now.

Also, we (finally) have initial test coverage which can even detect some bugs or better to say regressions (the tests are located at `/tests/`; they are not yet accessible standalone,
but we will do it soon).

The tests have found one regression after your changes:

```
$ bash run-tests.sh 
FAILED: [5] cht.sh :intro
TESTS/OK/FAILED 14/13/1
```

I will take a look at it.

**Comment by chubin** [comment]
It was this:

```
  File "/home/igor/cheat.sh/lib/colorize_internal.py", line 38, in _back_color
    if code == 0 or code.lower()=="white":
AttributeError: 'int' object has no attribute 'lower'
```

The problem is fixed now.
```
$ bash run-tests.sh 
TESTS/OK/FAILED 14/14/0
```

**Pull request merged**
