### PR TITLE
Remove hardcoded paths, add script to get sheets, fix requirements

### PR DESCRIPTION
**Pull request by bglopez**
This pull request will fix the hardcoded paths noted in issue #44, adds a script (not a very good one) that makes the cheatsheets folder and pulls in remote repos to populate it and also updates requirements.txt to add the additional needed requirements.

### CODE REVIEW

**Comment by chubin** [comment]
Thank you very much for the fixes. I've changed several values in lib/globals.py (made them conditional).
+ I moved `get-sheets.sh` to `share/scripts/`.
+ parametrized `PATH_LEARNXINY`.

We should fix several other minor things (e.g. documentation) before closing #44, 
but with your fixes we are much closer to this. Thank you very much for your help!

**Comment by bglopez** [comment]
No problem, I'll see what I can help out with. It may be easier to move defineable settings to a separate configuration and pull them in that way as opposed to using global.py

**Comment by chubin** [comment]
@bglopez I think yes, you are right, we should move the parameters (at least some of them)
to a configuration file.

I will extend the main readme file (README.md) with a new section soon,
where your changes will be extremely useful.

And another good news: we have some initial self-tests now, that means that extending and refactoring
of the project will be much easier now.

**Comment by bglopez** [comment]
@chubin I have some pending things re: Dockerizing this to run easily on a local machine and the associated documentation updates to match. I'll verify the latest pushes build cleanly and then make the PR with those changes.

**Comment by chubin** [comment]
@bglopez  Ok, now I see why you canceled the PR, but maybe it would be better to merge it instead, and then just add the missing fixes? It should not be too much, I suppose

**Pull request merged**
