### PR TITLE
Improved installation instructions

### PR DESCRIPTION
**Pull request by Albonycal**
`curl` using the `-s` 
and added missing `sudo`

### CODE REVIEW

**Comment by abitrolly** [comment]
`-s` silences error messages. No good.

**Comment by Albonycal** [comment]
> `-s` silences error messages. No good.

 it's harder to type password because of that output

**Comment by abitrolly** [comment]
Need a screencast to see before and after to give some opinion.

**Comment by Albonycal** [comment]
image

**Comment by abitrolly** [comment]
https://explainshell.com/explain?cmd=curl+-sS+google.com

**Comment by Albonycal** [comment]
> https://explainshell.com/explain?cmd=curl+-sS+google.com

that's exactly what I am doing in this PR 
lmao

**Comment by abitrolly** [comment]
I tried to point to `-S` option twice.
lmao

**Pull request merged**
