### PR TITLE
Test "production" container on Travis

### PR DESCRIPTION
**Pull request by abitrolly**
This fixes Travis build setup (but not tests).

https://github.com/containers/podman/issues/8257

### CODE REVIEW

**Comment by chubin** [comment]
@abitrolly To me it looks like the upstream cheat sheets were not fetched. Is it right?

**Comment by abitrolly** [comment]
@chubin if we talk about GitHub Actions test https://github.com/chubin/cheat.sh/runs/1389777947 then there are no steps to fetch cheat sheets. Just to run the tests.

https://github.com/chubin/cheat.sh/blob/ee0f4c494b82e6b66226c611d8e14b99c3177ff9/.github/workflows/tests-ubuntu.yml#L15-L19

**Comment by chubin** [comment]
Yes, you are right.

Now it misses the `log` directory: 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cheat.sh/log/fetch.log'
```

Strange, I thought we created it automatically

**Comment by abitrolly** [comment]
@chubin I bet logger can create the file, but it doesn't create directories.

**Comment by abitrolly** [comment]
@chubin I'd move the config dir to `~/.config/cht.sh` and the log to `~/.config/cht.sh/fetch.log`.

https://unix.stackexchange.com/questions/24347/why-do-some-applications-use-config-appname-for-their-config-data-while-other

What'd you say?

**Comment by chubin** [comment]
I meant the log directory. We created it expliciltly in the code if I remember it correctly

**Comment by chubin** [comment]
I've found it; we do it only in `bin/srv.py`

**Comment by chubin** [comment]
Ok, now the logdir should automatically be created

**Comment by abitrolly** [comment]
For me the right place way to create all those dirs is at some central place, like `config` object, after it is clear that logging is enabled.

**Comment by abitrolly** [comment]
Now sheets in #250 are fetched successfully, but test don't pass yet.

**Comment by chubin** [comment]
Yes we could create directories there, or in the installation script even.

Regarding the tests: do you see any difference in those lines?
They look absolutely identical to me. Probably they contain some ANSI formatting?

**Comment by abitrolly** [comment]
@chubin see raw logs https://pipelines.actions.githubusercontent.com/LRxDA6zDbjIX7FN9r9pNO1vpvCOU4YHfbKRBK26SfybxLIIjOp/_apis/pipelines/1/runs/24/signedlogcontent/3?urlExpires=2020-11-12T14%3A01%3A59.7481059Z&urlSigningMethod=HMACV1&urlSignature=pARRKrrgi%2Bf4Ormt%2BEb6Ip4o0t82ZBZmIoJq7QvYPfg%3D

**Comment by abitrolly** [comment]
Looks like raw logs URLs don't work. Here them attached.

[rawlog.txt](https://github.com/chubin/cheat.sh/files/5531050/rawlog.txt)

```
2020-11-12T12:03:52.2933039Z  [48;5;8m[24m btrfs [24m[0m
2020-11-12T12:03:52.2933674Z -[38;5;246;03m# create the subvolume /mnt/sv1 in the /mnt volume[39;00m
2020-11-12T12:03:52.2934222Z +[38;5;246m# create the subvolume /mnt/sv1 in the /mnt volume[39m
2020-11-12T12:03:52.2934899Z  [38;5;252mbtrfs[39m[38;5;252m [39m[38;5;252msubvolume[39m[38;5;252m [39m[38;5;252mcreate[39m[38;5;252m [39m[38;5;252m/mnt/sv1[39m
2020-11-12T12:03:52.2935215Z  
```
There is an additional ANSI suffix. Haven't looked into what it means yet. Maybe it sets background explicitly.

**Comment by abitrolly** [comment]
@chubin in this particular case it looks like `italic` attribute (03) is removed. Who produces this ANSI output? Maybe the lib got update?

**Comment by chubin** [comment]
Yes, that is true. Compare:

```
$ # Pygments==2.7.2
$ echo "# hello" | ve/bin/pygmentize -f terminal256 -l bash -P style=native | hexdump -C
00000000  1b 5b 33 38 3b 35 3b 32  34 36 3b 30 33 6d 23 20  |.[38;5;246;03m# |
00000010  68 65 6c 6c 6f 1b 5b 33  39 3b 30 30 6d 0a        |hello.[39;00m.|
0000001e
```

vs 

```
$ # 2.2.0+dfsg-1
$ echo "# hello" | pygmentize -f terminal256 -l bash -P style=native | hexdump -C
00000000  1b 5b 33 38 3b 35 3b 32  34 36 6d 23 20 68 65 6c  |.[38;5;246m# hel|
00000010  6c 6f 1b 5b 33 39 6d 0a                           |lo.[39m.|
00000018
```

vs 

```
# 2.3.1
$ echo "# hello" | pygmentize -f terminal256 -l bash -P style=native | hexdump -C
00000000  1b 5b 33 38 3b 35 3b 32  34 36 6d 23 20 68 65 6c  |.[38;5;246m# hel|
00000010  6c 6f 1b 5b 33 39 6d 0a                           |lo.[39m.|
00000018
```

We need to check the version of pygmentize that is used in the test

**Comment by chubin** [comment]
@abitrolly :tada: It works and it is green now!
We managed it. Very cool! Thank you Anatoli!

There is some minor problem in the Travis checks, probably the same that I've fixed today in Actions.

Do you have some arguments why we should keep both Travis and Github Actions? Or should we switch completely to Github Actions in your opinion?

**Comment by abitrolly** [comment]
@chubin Travis syntax is shorter. I just didn't have time to see how GitHub Actions run containers. Until that time Travis tests server + client, while GitHub Actions tests only client for now.

**Comment by chubin** [comment]
But Travis has currently the same problem with the dependency version

**Comment by chubin** [comment]
I will fix it; also I noted that in PRs in our current setup, Travis takes Dockerfile from master and not from the PR branch

**Pull request merged**
