### PR TITLE
Fix test timeouts on Travis

### PR DESCRIPTION
**Pull request by abitrolly**
This should fix current build failure with timeout
https://travis-ci.org/github/chubin/cheat.sh/builds/741308362#L402

### CODE REVIEW

**Comment by abitrolly** [comment]
@chubin this fixes timeouts in Travis test. The rest needs to be be debugged in separate PR.

https://travis-ci.org/github/chubin/cheat.sh/builds/741436275

**Comment by chubin** [comment]
@abitrolly why is it important if curl version is outdated or not?
Do you need some supernew feature in it?

**Comment by abitrolly** [comment]
@chubin yep, `--retry-all-errors` was added in 7.71.0 - https://curl.haxx.se/docs/manpage.html#--retry-all-errors

But Ubuntu only ships 7.68.0 - https://curl.se/download.html#LinuxUbuntu

**Comment by chubin** [comment]
Ok. To be honest, I didn't understand what is exactly the problem that we are trying to solve.
The service is not starting on time, or what exactly?

**Comment by abitrolly** [comment]
@chubin yes, when docker container is run, the port becomes open before the web server is started, and connecting to the port will get `Connection reset by peer` error. It is easy to reproduce.

```shell
$ podman run -d -p 9990 -it bash
$ curl localhost:9990
curl: (56) Recv failure: Connection reset by peer
```

**Comment by chubin** [comment]
Maybe we should use something like `while [[ $attempts -lt "$timeout" ]]; do` here,
as curl's man recommends it?

**Comment by abitrolly** [comment]
@chubin `wget` already does a better job here. I hoped I could check it with a Python script, but that didn't work https://github.com/urllib3/urllib3/issues/2037

**Comment by chubin** [comment]
Interesting. Actually, it is a pretty standard use-case, and I wonder why nobody stumbled upon this problem before

**Comment by abitrolly** [comment]
Because of the problems like this Google created Kubernetes.

**Comment by chubin** [comment]
No, I mean this bug in urllib3

**Comment by abitrolly** [comment]
Maybe the API to get timeouts with retries is complicated enough to keep people from reaching this far. :D

**Pull request merged**
