### PR TITLE
Updated Readme file to include C++

### PR DESCRIPTION
**Pull request by lepatrick714**
The picture was originally linked to your webpage. I placed the new one in the root directory.

### CODE REVIEW

**Comment by chubin** [comment]
Wait wait wait! We need to add some additional things to say that we support c++ (syntax highlightig, adaptor for learnxiny, + some minor things).

And the picture is generated automatically, so you don't need to do it manually,
just post here a link to a SVG-file with C++ logo (I'm not sure that we should use the logo of ISO C++ as C++ logo, may be use that instead: https://upload.wikimedia.org/wikipedia/commons/1/16/The_C%2B%2B_logo.svg?)

**Comment by lepatrick714** [comment]
Ahhh forgive me! I'll look into the codebase tonight to see if I can add those additions. 

I'm fine with that picture.

**Comment by chubin** [comment]
I've added some initial c++ support (not yet committed), could you test it?

What to test:

1. Syntax highlighting + your cheat sheets
2. :learn + :learn-cheat-sheets (if they were parsed correctly)

**Comment by lepatrick714** [comment]
Sounds good. I'll test it tonight.

**Comment by lepatrick714** [comment]
Hey @chubin, 

I've tested the two features and they work as expected! Dope!

**Comment by lepatrick714** [comment]
Closing this because the readme is already updated with the C++ cheats

**Pull request closed without merging**
