### PR TITLE
IDEA plugin implemented 

### PR DESCRIPTION
**Pull request by szymonprz**
Hi
I've just implemented a plugin for IntelliJ IDEA and other Jetbrains products, so could you add information about it to your main readme?
No configuration is needed for IDEA users to use this plugin and it detects context/programming language from current editor window. 
I plan to implement more features for this plugin, so then I will update your readme again :)

### CODE REVIEW

**Comment by szymonprz** [comment]
@chubin We missed it too :) 

1. First of all I need to add configuration option to enable/disable comments, then I will try to implement new view in IDEA to display multiple answers and to be able to switch between them
2. For now I don't need anything, but in case of any questions I will reach out to you directly
3. I'm not so active twitter user but you can find me by @szymon_prz
4. Of course I can make it, will try to find some time today or tomorrow
5. If configuration of comments is not so important from your point of view, we can make it when i will give you a demo video

**Comment by szymonprz** [comment]
@chubin and please upload idea-demo.gif provided in this pr to cheat.sh, because it's not available now and readme cannot display it

**Comment by szymonprz** [comment]
@chubin I've just made a small demo: https://imgur.com/a/hBFMd8u you can take it and post it with information about this plugin on twitter

**Comment by chubin** [comment]
Could you please fix several things in the demo:
1. Make it square so it would fit in the twitter format; it is ok if one half of the line will be cut (everybody understands that it is only a fragment). And the resolution could be bigger; it seems to me that the font is too small.
2. Either use >= 10 lines of code in the buffer from the beginning or chose some query, that it will stay < 10 after processing it, so the buffer will not be shifted at the end of the video because of that;
3. Could you make the video may be a little bit longer (but not much!), maybe with additional pause at the end (2-3 secs), so that the user has enough time to understand what is happening.
4. (Just an idea) Could it be some query more typical for Kotlin? Pattern matching is not quite typical, right? What about `read file`? And the answer is pretty short, I've just checked.
5. Are there any visual features of IDEA that the users will immediately recognize it when seeing the video for a second? You are scrolling your twitter feed (and you are an IDEA user); your eye meets the video with IKEA and the plugin "Oops. What is that it? It seems to be IDEA... Let me take a look". Or is your video is typical enough? (I am not IDEA user, so I can't just say)

And the rest is very good! Could you please update the video and we will post it?

Another question:

Is there some mode in IDEA where you can have a input field for a query?
The problem is that you not always can formulate your query, and you want to have some suggestions.
We are working on a new feature, that will show you suggestions as you type.
Could it possible to add this functionality to your plugin, as soon as it is available?
(from the server side)

**Comment by szymonprz** [comment]
Hi, I've just applied your suggestions and here is the video https://www.dropbox.com/s/w746x528ic6wpe8/idea-demo.mp4?dl=0 

Basically plugins for idea are implemented with usage of swing java library, it's not so flexible but as Ican see on the web there are some solutions how to implement such autocomplete field. 
Currently I'm working on displaying more answers to question so it shouldn't be a problem to extend it to provide autocomplete, just let me know when it would be available

**Comment by chubin** [comment]
Thank you for the video. I've reworked it a little, and create a picture based on it.
That is how it looks like:
text6289

Hope it conveys the idea.

If you like it, you may use it on your project page, or anywhere you want.

I've twittet about the plugin:

https://twitter.com/igor_chubin/status/1094301740692881409

I do not know how many IDEA users are among my followers, probably not so many, but there should be a couple of them. VSCode plugin gathered 39 likes. Let us how many likes will get the IDEA plugin :heart_eyes:

There are two things that could and should be implemented:
1. Auto completion (before you completed your query)
2. Similar questions/additional answers list (after you completed the query)
Please, think about implementation of these features on the plugin side.
We are currently working on their implementation on the server side.

**Pull request merged**
