### PR TITLE
Fix various typos

### LINKED ISSUE #169: Typos
$ __codespell . --ignore-words-list=ba,referer --skip=./.* --quiet-level=2__
```
./CONTRIBUTING.md:7: upsream  ==> upstream
./README.md:298: overriden  ==> overridden
./lib/fetch.py:4: Ths  ==> The, this
./lib/config.py:8: overriden  ==> overridden
./lib/config.py:26: overriden  ==> overridden
./lib/config.py:38: paramters  ==> parameters
./lib/config.py:142: pathes  ==> paths
./lib/adapter/adapter.py:16: Adapater  ==> Adapter
./lib/adapter/adapter.py:128: usefule  ==> useful
./lib/adapter/adapter.py:151: overriden  ==> overridden
./lib/adapter/git_adapter.py:15: methos  ==> methods, method
./lib/adapter/git_adapter.py:22: extenstion  ==> extension
./lib/adapter/git_adapter.py:58: adatpers  ==> adapters
./lib/adapter/question.py:33: fot  ==> for
./lib/adapter/cmd.py:37: beause  ==> because
./tests/results/6:95: ue  ==> due
./tests/results/25:11: wth  ==> with
./tests/results/16:11: wth  ==> with
./tests/results/8:98: overriden  ==> overridden
./tests/results/8:194: dependecies  ==> dependencies
./tests/results/8:285: Uknown  ==> Unknown
./tests/results/8:286: Suported  ==> Supported
./share/intro.txt:95: ue  ==> due
./share/ansi2html.sh:250: minimise  ==> minimise, minimize
./share/cht.sh.txt:98: overriden  ==> overridden
./share/cht.sh.txt:194: dependecies  ==> dependencies
./share/cht.sh.txt:285: Uknown  ==> Unknown
./share/cht.sh.txt:286: Suported  ==> Supported
```

### PR DESCRIPTION
**Pull request by waldyrious**
Fixes #169.

Note that one of the corrections was incorrect: "ue"->"due". I opened [codespell#1413](https://github.com/codespell-project/codespell/issues/1413) to track that issue.

### CODE REVIEW

**Comment by chubin** [comment]
@waldyrious Waldir, thank you for the fixes.
Do I understand it right, that the check were automatic, and they will in run in future too?

**Comment by waldyrious** [comment]
The check was the result of cloning the repo and manually running the `codespell` command on the codebase, so it won't run again automatically. I suppose it could be added to a CI script to run automatically in every PR.

**Comment by chubin** [comment]
@waldyrious Ok, than it is even better than I thought. Thank you twice
There are some bots that automatically scan popular repositories for typical (spelling and coding) failures, and I thought your PR was of such sort

**Comment by waldyrious** [comment]
Hahah, no, it was manual. To be fair I've been confused with a bot more than once in GitHub PRs, because I tend to enjoy fixing small issues and performing maintenance tasks that not many people care about. Thanks for the merge!

**Pull request merged**
