### PR TITLE
refactor limits.py

### PR DESCRIPTION
**Pull request by StrikingLoo**
Good morning!
As I see my last PR went through, I decided to do another small refactor. This time it was the "limits.py" package's turn. 
Changes:
*Make code for 'ip_check' clearer by abstracting logic away into functions.
*Make comments prettier and correct typo.
*Make the intervals generation a bit easier and less verbose.

I hope you like the changes!

### CODE REVIEW

**Comment by StrikingLoo** [comment]
By the way, I wasn't able to run the tests. I'm not sure what I'm doing wrong.

**Comment by StrikingLoo** [comment]
I also wasn't sure enough, but shouldn't _clear_counters_if_needed use integer division? And isn't this whole thing in Python 3, with / being float division?

**Comment by chubin** [comment]
@StrikingLoo Luciano, thank you very much for your PR.
It is much better now, but please fix these two minor things first.

Regarding integer division, yes, you are right. Probably we should use `//` instead.

Regarding the tests, if you are only starting the test script, it does not test your current code, it tests the code running at cheat.sh (what makes not so much sense). To run the tests locally you should run the test server in a docker container (docker support will be added soon), or start a test server manually (not so straightforward process, at least not yet), or I can prepare a test environment for you.

What would you prefer?

**Comment by StrikingLoo** [comment]
Good morning! I didn't realize I was using self, I will correct it soon. 
About the test environment, I don't really know much about Docker or how to get the server started, so I would love it if you made it easier to run a local server for testing (or just told me how to).
Thanks!

**Comment by chubin** [comment]
I will prepare a test environment for you and give you access to it.
I think it should be the best solution.

**Comment by StrikingLoo** [comment]
I think new commits get added automatically. 
Please check if this works now.
Thanks for the feedback!

**Comment by chubin** [comment]
Please check variable names (`ip`/`ip_addr` etc.) + check function names `_get_limit`/`get_limit` + check code indentation.

What editor do you use?
If it is Vim, I recommend you the syntastic + pylint combination: many obvious mistakes will be found immediately.

**Comment by StrikingLoo** [comment]
I was actually using gedit, I just didn't realize the variable names had changed. Now I made it more consistent. I will look into installing syntastic and pylint later, I've never installed a vim package.

**Comment by chubin** [comment]
Even if you would have to invest some time in it, you would save much more time in the future.
Pylint + syntastic is a great combination. (and you could use cheat.sh-vim plugin too).

**Pull request merged**
