### PR TITLE
Add link to Visual Studio Code extension

### PR DESCRIPTION
**Pull request by mre**
I wrote a little extension for Visual Studio Code. 
It doesn't require any configuration and automatically detects programming language from current editor window. Hope you like it. 😃

### CODE REVIEW

**Comment by chubin** [comment]
Perfekt! Sehr gut gemacht. Visual Studio Code ist das wichtigste (und Sublime auch).


Very cool extension! Unfortunately, I could not try it myself, but it seems to be a very nice thing.

I have several questions/suggestions:

1. Do you plan to improve the plugin?
2. Have you read about cheat.sh-vim and what features does it support?
3. What do you think about these features/how could the following be done:
* Toggle comments on/off (`?Q`)
* Switch to the next possible answer/snippet (`/1`, `/2` and so on)
* Send error messages/warnings as queries.

And thank you very much for the great plugin once again.

**Comment by mre** [comment]
Hey, thanks!

1. Absolutely! I'm also looking for contributors, so if anybody wants to join, feel free to reach out.
2. cheat.sh-vim looks very powerful. There are a few think I'd like to add, for example opening the response from cheat.sh in an unnamed editor instead of the current position in the current window.
3. About the features:

* Toggle comments on/off (`?Q`): Could add a config option for that. Should be straightforward.
* Switch to the next possible answer: I guess one way could be to offer a little preview window like Gitlens does it for branch selection. Open for suggestions here as I'm not sure what would be the most "native" VSCode way to do that.
* Send error messages/warnings as queries: Great idea! I could add a command to search for the highlighted text (e.g. `Snippet: Search selection`). As for error message, I'm not sure how to grab those from the command line. In VSCode, we've got "output", "debug console" and "terminal" and each can contain things to search for. Not sure how we could do this yet, but I'll create a ticket for it.

**Comment by mre** [comment]
Update: [Created a few issues](https://github.com/mre/vscode-snippet/issues) for the things you mentioned. 😄

**Comment by chubin** [comment]
What do you mean with this:

> opening the response from cheat.sh in an unnamed editor instead of the current position in the current window.

In Vim you can get the answer in three different ways: pager, the current buffer, a new buffer. Is it not that?

And about toggling the comments on/off: it would be great to make just in time, for each query, 
not configuring one time forever, because it depends on the answer, whether you need the comments or not.

Maybe after we announce the plugin and people will start to install it, we will get more info about that how exactly it should be done.

**Comment by mre** [comment]
> In Vim you can get the answer in three different ways: pager, the current buffer, a new buffer. Is it not that?

Exactly. In VS Code there is no concept of a buffer as far as I know. I guess the thing that comes closest is a new editor window. Might be mistaken, though.

> And about toggling the comments on/off: it would be great to make just in time, for each query,
not configuring one time forever, because it depends on the answer, whether you need the comments or not.

Yup, that's an important point. Not sure how to do that yet. We could do it with two commands like`Snippet: Lookup` and `Snippet: Find`, but I kinda want to avoid that as the difference might not be directly apparent. If I find the time, I will look how other plugins resolved that situation.

**Comment by chubin** [comment]
@mre 

Hi Matthias,
I've seen that you've have done pretty many improvements in your beautiful plugin.
Is it ready for release? Or do you want to add several other features before?
Should I announce it or is it too early?

I would like to share some news/questions/ideas with you:

1)
How exactly do you detect current context (programming language), that should be used for the query? Say, I am editing a JavaScript-file and do a query. What URL will be queried?
We have a new query type now:
```
/EDITOR:LANGUAGE/QUERY
```
e.g.
```
/vim:javascript/convert+to+int
```
that is automatically rewritten on the server side into a query in the right context.
The server knows the mapping "editor names"-"cheat.sh names" so this mapping should not bother the plugin anymore.
For VSCode, the prefix is `vscode`.
(the mapping for VScode is not yet added to the server though; we should add if you like the new query type).

2)

We have added a table where all cheat.sh editor plugins and their features are compared.

https://github.com/chubin/cheat.sh#editors-integration

Is everything correct here? Or does the plugin support some features that are not marked/mentioned in the table?

3)

Do you want to participate in the discussions with other plugin/cheat.sh developers, when we are discussing the plugins/cheat.sh features/feature requests/bugs/development plans?

4) 

We are working on the next cool cheat.sh features, some of them could be really interesting for the community (and for the plugin users). Would you like to discuss them?

5) 

(the questions from the beginning of the message)

I hope to hear from you soon, Mathias,
and thank you for the beautiful plugin

**Comment by mre** [comment]
Hey there @chubin,

> Is it ready for release? Or do you want to add several other features before?

It's definitely not feature-complete, but I think the functionality that is already there should keep working (I use it daily). So it should be ready for a 1.0 release I think.

> Should I announce it or is it too early?

Sure that would be nice. Maybe we find some additional contributors this way. 😃 

> How exactly do you detect current context (programming language)?

There's [a VSCode API call for it](https://github.com/mre/vscode-snippet/blob/master/src/extension.ts#L6). 

> We have a new query type now.

I like itAdded it to the VSCode plugin. 👍

 > We have added a table where all cheat.sh editor plugins. Is everything correct here? 

Toggling comments was missing. Created a [PR here](https://github.com/chubin/cheat.sh/pull/93).

> Do you want to participate in the discussions with other plugin/cheat.sh developers, when we are discussing the plugins/cheat.sh features/feature requests/bugs/development plans?

Time is always limited, but we can try. Will send you a mail with my contact data for further discussion. 😉 

Cheers,
Matthias

**Comment by chubin** [comment]
> Sure that would be nice. Maybe we find some additional contributors this way.

Perfect! I will do the announcement then

> There's a VSCode API call for it.

The problem is actually that some programming languages names that VSCode uses internally, do not correspond to the cheat.sh programming languages names. At least not in all cases.
There are some aliases (such as `javascript` for `js`, for example), but we can't guarantee that all programming languages names of VSCode are covered by this aliases.

See, for example, how Emacs major mode names are translated into programming languages names
(thanks to @davep for the idea and for the Emacs translation table):

https://github.com/chubin/cheat.sh/blob/199f4bfbe5aeee837c89ab63e847d9e8d10a7a67/lib/languages_data.py#L208

The question is how do we get the same table for VSCode?
Do you have some list of the programming languages names (as VSCode knows them).
Where could we get such list?

**Comment by mre** [comment]
Does this help? https://code.visualstudio.com/docs/languages/identifiers

**Pull request merged**
