### PR TITLE
First draft of manual page for cht

### PR DESCRIPTION
**Pull request by grayed**
Not intended for commit right now, but suggestions (especially on TODO items) are welcome.

### CODE REVIEW

**Comment by grayed** [comment]
I should note that on OpenBSD I found no programs naming "cht" neither in base system or in Ports. Thus I think "cht.sh" could be renamed to "cht" (actually I'm using it this way all the time :) ).

**Comment by chubin** [comment]
Actually, the idea behind the cht.sh client is that its called exactly as the server itself.
The cheat.sh project was developed as a part of a bigger project, where console services at the end of the day can be called directly as programs (we are working on that in curl; it is not yet fully implemented).

That will mean that any console service could be called directly by its name, and its arguments will be rewrite just in time (by curl) into the query string. 

To use curl in this mode, it should be called with the name of the service (which should be a hardlink of a symlink to curl).

Say: 
```
ln -s /usr/bin/curl /usr/bin/cht.sh
ln -s /usr/bin/curl /usr/bin/wttr.in
ln -s /usr/bin/curl /usr/bin/rate.sx
cht.sh python copy file
wttr.in Moscow
rate.sx btc
```

Of course, that's true, that cht.sh is currently a standalone script, but we are trying to emulate the look and feel of this future service-as-a-command thing.

**Comment by grayed** [comment]
Hm, okay. I really need to get the whole picture in my head first then.

**Comment by chubin** [comment]
@grayed Vadim, your man is a great thing anyway, the only change that we should do here is rename it to cht.sh.1 and replace cht with cht.sh. Please reopen the pull request

**Pull request closed without merging**
